### PR TITLE
Updated SCP Module

### PR DESCRIPTION
**Pull request by MeestorX**
Adds all available "set" commands and some feedback ability. 
Command list is in "CL5 SCP Parameters-1.txt" and "TF5 SCP Parameters-1.txt". Select available commands by starting line with OK, any other pair of characters to ignore that command.

### CODE REVIEW

**Comment by MeestorX** [comment]
My first time pushing to github, so maybe I did something incorrectly, however, if I click “view changes” on this page I see all the new files and changes.
Is there something else I need to do?

**Comment by krocheck** [comment]
I see the code.

First issue that will need to be addressed is your naming convention.  You're using UpperCamelCase, and you should be using lowerCamelCase, e.g.: SCPcmd > scpCmd, NewConsole > newConsole

Second issue is that this includes, by my read, breaking changes to the actions.  By that I mean that existing users with actions already configured would have to recreate all of those actions.  This is because the action keys (action.action) change from, as an example, "InChLevel" to "MIXER:Current/InCh/Fader/Level".  This will need to be addressed with an upgrade script.

**Comment by MeestorX** [comment]
Thank you for the review. I can make those convention changes pretty easily to the code. Should even acronyms like SCP which are capitalized in the real world still be lowerCamelCase?

I have no idea how to create an upgrade script. I understand the policy and fully support it, however, I expect that there are very few users of this module, since the original only had a few functions. Anyone using it could recreate their buttons (with additional capabilities) in a few minutes, and I'd even offer to do it for them if need be.
That being said, since I'm new to this, learning how to create an upgrade script is probably something I should learn. Can you point me to the instructions?

**Comment by krocheck** [comment]
Correct ... SCP can be shown as all lower case.

Regardless of user-base size, we don't want to knowing do a release with breaking changes.  Here's a search to find examples of upgrade scripts in place.  Some are just a config updates but others like qlab, eventmaster, and hyperdeck have good starting points.  https://github.com/search?q=org%3Abitfocus+addUpgradeScript&type=Code

**Comment by MeestorX** [comment]
Copy that. Thank you. I'll have a closer look at those modules. It seems like it's a conversion of the names of the actions that is required? I take it to test this I would need to have both versions of the module and create some actions in the old version and then try running the new version and see how they convert?

**Comment by MeestorX** [comment]
One issue is it's not possible to test the old vs the new offline. The original SCP module requires the mixer to be online and connected. My version allows setting up actions while offline. So... I can't set up any actions to test with the original module. I can only guess at whether an upgrade script would work or not until I am in front of this mixer again.

**Comment by MeestorX** [comment]
Also, the old options have different names than the new. Not sure how to return an action that has different parameters (names, not values) than the ones passed to the UpgradeScript function. It seems like the UpgradeScript edits the original (old) actions which have different properties than the new actions. Maybe it "just works", but without testing, who knows. The scripts you linked don't appear to be dealing with a change in parameter names...

**Comment by MeestorX** [comment]
2nd commit pushed.

**Comment by MeestorX** [comment]
Let me know if this looks ok.

**Comment by MeestorX** [comment]
I'm sorry - I'm still learning how to use GitHub. Is there something I need to do to resolve the conflicts?

**Comment by MeestorX** [comment]
Ok, I think I resolved the conflicts, but I'm not clear why there were conflicts in the first place. Is there something I should do to avoid conflicts in the future?

**Pull request merged**
